### ISSUE TITLE
Warnings from schema__itemlocation.inc and schema__license_formatter.inc

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal_file#11]
The following two warnings appear on a file page:

Warning: A non-numeric value encountered in tripal_format_bytes() (line 153 of /var/www/2020-02-18/drupal-7.69/sites/all/modules/tripal/tripal/api/tripal.files.api.inc).

Notice: Undefined index: empty in theme_table() (line 2003 of /var/www/2020-02-18/drupal-7.69/includes/theme.inc).Notice: Undefined index: empty in theme_table() (line 2003 of /var/www/2020-02-18/drupal-7.69/includes/theme.inc).

The first warning appears when the file is a URL and the file size is a null string in ```schema__itemlocation.inc```

The second notice appears because a value for ['empty'] is not defined in ```schema__license_formatter.inc```

See pull request #12 for corrections for these issues.

**Comment by spficklin** [comment]
Thanks for pointing out the issue and the pull request to fix it!  I think this is now fixed so closing.
