### ISSUE TITLE
sio__references_file warnings and display problems

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal_file#14]
I have a file with a reference to an organism defined in the ```chado.organism_file``` table.
I am seeing two warnings:
    Notice: Trying to get property 'type_id' of non-object in sio__references_file->load() (line 214 of /var/www/2020-02-18/drupal-7.69/sites/all/modules/tripal_file/includes/TripalFields/sio__references_file/sio__references_file.inc).
    Notice: Trying to get property 'name' of non-object in sio__references_file->load() (line 220 of /var/www/2020-02-18/drupal-7.69/sites/all/modules/tripal_file/includes/TripalFields/sio__references_file/sio__references_file.inc).
and the field displays incompletely with no name, and the infraspecific type omitted
![before](https://user-images.githubusercontent.com/8419404/111075534-71050200-84b6-11eb-8db5-8ebb38df2086.png)

I'll submit a pull request to fix

**Comment by spficklin** [comment]
I believe this is fixed, so closing out.  Thanks again for the PR!
