### ISSUE TITLE
Stray <php inserted

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal_file#7]
In the tripal_file.theme.inc file, there is a lone `<?php` followed by EOF which gets misinterpreted by PHP and inserted into pages, including AJAX responses.

**Comment by dsenalik** [comment]
I just figured out where this was coming from too. It also shows up when enabling the tripal_file module

drush pm-enable tripal_file
The following extensions will be enabled: tripal_file
Do you really want to continue? (y/n): y
**<?php**tripal_file was enabled successfully.

**Comment by spficklin** [comment]
Thanks both of you for discovering and providing a fix.  We didn't have this problem during development.  Very odd.
