### ISSUE TITLE
Load EDAM Vocabulary - incorrect response from EBI

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal_file#8]
When launching the job to load the EDAM vocabulary, the server gets a bad response from EBI:
```Performing EBI OLS Lookup for: EDAM_data:0005
Cannot find the ontology via an EBI OLS lookup: EDAM_data. \nWe tried to access: http://www.ebi.ac.uk/ols/api/ontologies/EDAM_dataEBI Reported: Resource not found. Consider finding the OBO file for this ontology and manually loading it first.
Cannot find the term via an EBI OLS lookup: EDAM_data:0005. We tried to access: "http://www.ebi.ac.uk/ols/api/ontologies//terms/0005" EBI Reported: No message available. Consider finding the OBO file for this ontology and manually loading it first.
Performing EBI OLS Lookup for: EDAM_data:0006
Cannot find the term via an EBI OLS lookup: EDAM_data:0006. We tried to access: "http://www.ebi.ac.uk/ols/api/ontologies//terms/0006" EBI Reported: No message available. Consider finding the OBO file for this ontology and manually loading it first.
Performing EBI OLS Lookup for: EDAM_data:0007
Cannot find the term via an EBI OLS lookup: EDAM_data:0007. We tried to access: "http://www.ebi.ac.uk/ols/api/ontologies//terms/0007" EBI Reported: No message available. Consider finding the OBO file for this ontology and manually loading it first.
```

This continues on for every term (~3000 - http://edamontology.org/EDAM.obo), and then the same for 'format', 'operation', and 'topic'.

Letting it run to completion (instead of cancelling it) results in a Division by Zero error from TripalImporter.inc:646 followed by evidently not loading any type defs or terms:

```
Step 3: Loading type defs...
Step 4: Loading terms... %. Memory: 46,783,152 bytes.
```

 The double slash in the URL does not seem to be the cause.

**Comment by spficklin** [comment]
Oh @Ferrisx4 . I'm sorry.  The problems here are related to the OBO Loader.  There is a PR to fix it here:  https://github.com/tripal/tripal/pull/1117.

Perhaps you could now, pull that code from the PR and retest it?  That would be sufficient as a functional test for that PR

**Comment by Ferrisx4** [comment]
Hi @spficklin, I pulled the PR and tested it. It was successful other than a few warnings during step #4:
```
Step 4: Loading terms... %. Memory: 59,168,560 bytes.
Cannot add an Alt ID without an accession: 'topic_0197'
Cannot add an Alt ID without an accession: 'topic_3076'
Cannot add an Alt ID without an accession: 'topic_3040'
Step 5: Cleanup...100.00 %. Memory: 59,433,896 bytes. ```

**Comment by spficklin** [comment]
Yeah, those warnings are from badly formatted alt_ids in the OBO. I'm not sure if those were historically made incorrectly or if there were entered into the OBO incorrect.  But it doesn't inhibit loading of the vocabulary.

**Comment by spficklin** [comment]
Would you mind leaving a comment about the successful test on the PR?  I'll mark it has having been approved and that should just trigger one more code review.

**Comment by spficklin** [comment]
I think this issue is now resolved.
